package com.cardgame.lwjgl3;


import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.lang.management.ManagementFactory;
import java.util.ArrayList;

/**
 * macOS / JVM compatibility helper generated by gdx-liftoff.
 *
 * <p>On macOS, LWJGL3 requires the JVM to be started with
 * {@code -XstartOnFirstThread}. If the current JVM was not launched with
 * that flag, this helper re-launches the process with it.
 */
public final class StartupHelper {

    private static final String JVM_RESTARTED_ARG = "jvmIsRestarted";

    private StartupHelper() {}

    /**
     * @return {@code true} if a new JVM was started (caller should {@code return} immediately),
     *         {@code false} if we are already running on the correct JVM.
     */
    public static boolean startNewJvmIfRequired() {
        String os = System.getProperty("os.name").toLowerCase();
        if (!os.contains("mac")) return false;

        // Already restarted?
        if (System.getProperty(JVM_RESTARTED_ARG) != null) return false;

        // Check if -XstartOnFirstThread is already active
        for (String arg : ManagementFactory.getRuntimeMXBean().getInputArguments()) {
            if (arg.equals("-XstartOnFirstThread")) return false;
        }

        // Restart with the required flag
        try {
            ArrayList<String> cmd = new ArrayList<>();
            cmd.add(ProcessHandle.current().info().command().orElse("java"));
            cmd.add("-XstartOnFirstThread");
            cmd.add("-D" + JVM_RESTARTED_ARG + "=true");
            cmd.addAll(ManagementFactory.getRuntimeMXBean().getInputArguments());
            cmd.add("-cp");
            cmd.add(System.getProperty("java.class.path"));
            cmd.add(Lwjgl3Launcher.class.getName());

            ProcessBuilder pb = new ProcessBuilder(cmd);
            pb.redirectErrorStream(true);
            Process p = pb.start();

            try (BufferedReader reader = new BufferedReader(new InputStreamReader(p.getInputStream()))) {
                String line;
                while ((line = reader.readLine()) != null) System.out.println(line);
            }
            p.waitFor();
        } catch (Exception e) {
            e.printStackTrace();
        }
        return true;
    }
}
